---
# file: fsl/tasks/main.yml

# sudo apt-get update
# DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
# sudo apt-get upgrade -y

## install any utilities

- name: "Install aptitude"
  apt: >
    update_cache=true
    name='{{ item }}'
    state='{{ fsl_state }}'
  with_items:
    - aptitude
  tags: [ 'packages', 'utilities' ]

## upgrade

- name: "apt-get upgrade, keep old configs, use new config when no old config exists"
  apt:
    upgrade: 'yes'
    dpkg_options: 'force-confold,force-confdef'
  when: fsl_state == 'present'

## dist-upgrade

# DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" dist-upgrade

- name: "apt-get dist-upgrade, keep old configs, use new config when no old config exists" 
  apt:
    update_cache: true
    upgrade: 'dist'
    dpkg_options: 'force-confold,force-confdef'
  when: fsl_state == 'present'

## Add Neurodebian

- name: install apt-key for neurodebian
  apt_key: >
    keyserver="hkp://pgp.mit.edu:80"
    id="0xA5D32F012649A5A9"
    state='{{ fsl_state }}'

# Add specified repository into sources list using specified filename.
#
# is this really idempotent?

- apt_repository:
    mode: 0644
    repo: deb http://neuro.debian.net/debian data main contrib non-free
    state: '{{ fsl_state }}'
    filename: 'neurodebian.sources' # .list is appended by the module
    update_cache: yes

- apt_repository:
    mode: 0644
    repo: deb http://neuro.debian.net/debian {{ ansible_distribution_release }} main contrib non-free
    state: '{{ fsl_state }}'
    update_cache: yes
    filename: 'neurodebian.sources'
  when: ansible_distribution == 'Ubuntu'

- name: "update apt cache"
  apt: >
    update_cache=true
    cache_valid_time=43200
  tags: [ 'packages' ]

## install fsl

- name: "Install (or remove) 'fsl'"
  apt: >
    name='{{ item }}'
    state='{{ fsl_state }}'
  with_items:
    - fsl
  tags: [ 'packages', 'utilities' ]

## Users configruation

