---
# tasks file for ansible-role-fsl

## prepare base OS

# sudo apt-get update
# DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
# sudo apt-get upgrade -y
### install any utilities

- name: "Install aptitude"
  apt: >
    update_cache=yes
    name='{{ item }}'
    state='{{ fsl_state }}'
  with_items:
    - aptitude
  tags: [ 'packages', 'utilities' ]

- name: "apt-get upgrade, keep old configs, use new config when no old config exists"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: 'yes'
    dpkg_options: 'force-confold,force-confdef'
  when: fsl_state == 'present'

# sudo apt-get dist-upgrade -y
# DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" dist-upgrade

- name: "apt-get dist-upgrade, keep old configs, use new config when no old config exists" 
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: 'dist'
    dpkg_options: 'force-confold,force-confdef'
  when: fsl_state == 'present'

### install any utilities

# this should work but does not!
#- name: install apt-key for neurodebian
#  apt: >
#    update_cache=yes
#    name='{{ item }}'
#    state='{{ fsl_state }}'

- name: install apt-key for neurodebian
  apt_key: >
    keyserver="hkp://pgp.mit.edu:80"
    id="0xA5D32F012649A5A9"
    state='{{ fsl_state }}'

# Add specified repository into sources list using specified filename.

- apt_repository:
    mode: 0420
    repo: deb http://neuro.debian.net/debian data main contrib non-free
    state: '{{ fsl_state }}'
    update_cache: yes
    filename: 'neurodebian.sources.list'
    update_cache: yes

- apt_repository:
    mode: 0420
    repo: deb http://neuro.debian.net/debian {{ ansible_distribution_release }} main contrib non-free
    state: '{{ fsl_state }}'
    update_cache: yes
    filename: 'neurodebian.sources.list'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: "update apt cache"
  apt: >
    update_cache=yes
    cache_valid_time=43200
  tags: [ 'packages' ]

## install fsl

- name: "Install (or remove) 'fsl'"
  apt: >
    update_cache=yes
    name='{{ item }}'
    state='{{ fsl_state }}'
  with_items:
    - fsl
  tags: [ 'packages', 'utilities' ]

## Users configruation

- name: "get remote systems users by UID range"
  shell: >
    ls /home/users
  changed_when: false
  register: users_in_home_users_dir
  when: fsl_state == 'present'

  tags: ["test"]

- debug: var=users_in_home_users_dir
  tags: ["test"]
  when: fsl_state == 'present'

- name: "Capture users groups"
  shell: >
    id -G {{ item }}
  changed_when: false
  register: users_groups
  with_items: users_in_home_users_dir.stdout_lines
  when: fsl_state == 'present'
  tags: ["test"]

- debug: var=users_groups
  when: fsl_state == 'present'
  tags: ["test"]

- name: Print test
  debug:
    msg="{{ item.item }} is a member of gid {{ fsl_users_gid }}"
  register: group_members
  when: "'{{ fsl_users_gid }}' in '{{ item.stdout }}'"
  with_items: "{{ users_groups.results }}"
  when: fsl_state == 'present'
  tags: ["test"]

- debug: var=group_members
  when: fsl_state == 'present'
  tags: ["test"]

